import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireAccess, canSupervise } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';
import { updateProduct, saveIdentifier, deleteIdentifier, deleteRelation, savePlatform, deletePlatform, deleteProduct } from '@/app/actions/products';
import { RelationEditor } from '@/components/relation-editor';
import { ConfirmForm } from '@/components/confirm-form';
import { logUserMessage } from '@/lib/messages';
import { label, productTypeLabels, relationTypeLabels } from '@/lib/labels';
import { SubmitButton } from '@/components/submit-button';
import { STOCK_UNITS, isStockUnit, unitLabel } from '@/lib/units';

type Product = { id: string; warehouse_id: number; product_code: string; product_type: string; source_name: string; display_name: string; packing_size_raw: string | null; base_stock_unit: string; active: boolean; source_sheet: string | null; source_row: number | null; raw_source: Record<string,unknown> | null; import_batch_id: string | null };
type Identifier = { id: string; kind: string; value: string; source: string; approved: boolean };
type Relation = { id: string; source_product_id: string; target_product_id: string; relation_type: string; note: string | null; source_text: string | null; source_kind: string; source_review_id: string | null };
type Platform = { id: string; platform_id: string; source_text: string | null; source_kind: string; source_review_id: string | null; ci_platforms: { platform_key: string; display_name: string } | null };
type Balance = { lot_id: string; lot_number: string; expiry_date: string; location_id: string; balance: number };
type Reorder = { mode: string | null; usable_stock: number; rop: number | null; suggested_order: number | null; missing_reason: string | null };
type ImportResolution = { review_id: string; resolution_type: string; raw_source_value: string | number | null; approved_decision: Record<string, unknown>; resolution_note: string; approval_source: string; recorded_at: string };

function approvedResolutionText(resolution: ImportResolution): string {
  const decision = resolution.approved_decision;
  if (decision.kind === 'product_relationship') {
    return `${String(decision.source_ref_current)} → ${String(decision.relation_type)} → ${String(decision.target_ref_current)}`;
  }
  if (decision.kind === 'unassigned') return 'คงความสัมพันธ์ Product และ Platform เป็น unassigned';
  if (decision.kind === 'product_data_correction') return String(decision.approved_value);
  if (decision.kind === 'product_type_override') return String(decision.approved_value);
  if (decision.kind === 'product_platform_override') return `${(decision.target_platform_keys as string[]).join(' + ')} เท่านั้น`;
  return `ยืนยันประเภท ${String(decision.approved_value)} โดยไม่แก้ค่า catalog`;
}

export default async function ProductDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; saved?: string }> }) {
  const { id } = await params;
  const query = await searchParams;
  const access = await requireAccess();
  const client = await createClient();
  if (!client) notFound();
  const { data: productData, error } = await client.from('ci_products').select('id,warehouse_id,product_code,product_type,source_name,display_name,packing_size_raw,base_stock_unit,active,source_sheet,source_row,raw_source,import_batch_id').eq('id',id).single();
  if (error || !productData) notFound();
  const product = productData as Product;
  const warehouse = access.warehouses.find(w => Number(w.id) === product.warehouse_id);
  if (!warehouse) notFound();
  const editable = canSupervise(warehouse.role);
  const [identifierResult, relationResult, platformResult, balanceResult, optionsResult, platformOptionsResult, reorderResult, locationResult, lotResult] = await Promise.all([
    client.from('ci_product_identifiers').select('id,kind,value,source,approved').eq('product_id',id).order('kind'),
    client.from('ci_product_relations').select('id,source_product_id,target_product_id,relation_type,note,source_text,source_kind,source_review_id').eq('source_product_id',id).order('relation_type'),
    client.from('ci_product_platforms').select('id,platform_id,source_text,source_kind,source_review_id,ci_platforms(platform_key,display_name)').eq('product_id',id),
    client.from('ci_stock_balances').select('lot_id,lot_number,expiry_date,location_id,balance').eq('product_id',id).gt('balance',0).order('expiry_date'),
    client.from('ci_products').select('id,product_code,display_name,product_type').eq('warehouse_id',warehouse.id).eq('active',true).order('product_code').limit(250),
    client.from('ci_platforms').select('id,platform_key,display_name').eq('warehouse_id',warehouse.id).order('display_name'),
    client.from('ci_reorder_status').select('mode,usable_stock,rop,suggested_order,missing_reason').eq('product_id',id).maybeSingle(),
    client.from('ci_locations').select('id,code,name').eq('warehouse_id',warehouse.id).limit(200),
    client.from('ci_stock_lots').select('id').eq('product_id',id).limit(200),
  ]);
  const identifiers = (identifierResult.data ?? []) as Identifier[];
  const relations = (relationResult.data ?? []) as Relation[];
  const platforms = (platformResult.data ?? []) as unknown as Platform[];
  const balances = (balanceResult.data ?? []) as Balance[];
  const options = (optionsResult.data ?? []) as { id: string; product_code: string; display_name: string; product_type: string }[];
  const platformOptions = (platformOptionsResult.data ?? []) as { id: string; platform_key: string; display_name: string }[];
  const reorder = reorderResult.data as Reorder | null;
  const locationMap = new Map((locationResult.data??[]).map(l=>[l.id,l]));
  const lotIds = (lotResult.data??[]).map(l=>l.id);
  const movementResult = lotIds.length ? await client.from('ci_stock_movement_lines').select('transaction_id,quantity_delta').in('lot_id',lotIds).order('created_at',{ascending:false}).limit(10) : {data:[],error:null};
  const txIds = [...new Set((movementResult.data??[]).map(m=>m.transaction_id))];
  const txResult = txIds.length ? await client.from('ci_stock_transactions').select('id,kind,purpose,created_at').in('id',txIds) : {data:[],error:null};
  const txMap = new Map((txResult.data??[]).map(tx=>[tx.id,tx]));
  const optionMap = new Map(options.map(p => [p.id,p]));
  const currentRef = identifiers.find((item) => item.kind === 'REF_CURRENT')?.value;
  const resolutionResult = product.import_batch_id && currentRef
    ? await client.from('ci_import_review_resolutions').select('review_id,resolution_type,raw_source_value,approved_decision,resolution_note,approval_source,recorded_at').eq('batch_id',product.import_batch_id).eq('source_product_ref',currentRef).order('review_id')
    : { data: null, error: null };
  const importResolutions = (resolutionResult.data ?? []) as ImportResolution[];
  const dataError = identifierResult.error ?? relationResult.error ?? platformResult.error ?? balanceResult.error ?? optionsResult.error ?? platformOptionsResult.error ?? reorderResult.error ?? locationResult.error ?? lotResult.error ?? movementResult.error ?? txResult.error ?? resolutionResult.error;
  return <main className="grid gap-6 max-w-[1100px]"><div><Link href={`/products?warehouse=${warehouse.code}`} className="muted text-sm">← สินค้าทั้งหมด</Link><div className="mt-5 flex items-start justify-between gap-4 flex-wrap"><div><p className="eyebrow mb-2">{warehouse.name} · {label(productTypeLabels,product.product_type)}</p><h1 className="page-title">{product.display_name}</h1><p className="muted mt-2 font-mono">{product.product_code}</p></div><span className="badge">{product.active ? 'ใช้งาน' : 'ปิดใช้งาน'}</span></div></div>
    {query.error && <p className="error" role="alert">{query.error}</p>}{query.saved && <p className="notice" role="status">บันทึกแล้ว</p>}{dataError && <p className="error" role="alert">อ่านข้อมูลบางส่วนไม่สำเร็จ: {logUserMessage('product', dataError)}</p>}
    <section className="surface p-5 sm:p-7"><h2 className="text-lg font-extrabold mb-5">Identity</h2><dl className="grid sm:grid-cols-2 gap-4 text-sm"><div><dt className="muted">Product Code</dt><dd className="font-bold">{product.product_code}</dd></div><div><dt className="muted">ประเภท</dt><dd className="font-bold">{label(productTypeLabels,product.product_type)}</dd></div><div><dt className="muted">ชื่อจากแหล่งข้อมูล</dt><dd className="font-bold">{product.source_name}</dd></div><div><dt className="muted">หน่วยนับสต็อก</dt><dd className="font-bold">{unitLabel(product.base_stock_unit)}</dd></div></dl>{editable && <form action={updateProduct} className="grid sm:grid-cols-2 gap-4 mt-6 pt-6 border-t border-line"><input type="hidden" name="id" value={id}/><label className="field">ชื่อที่แสดง<input className="input" name="display_name" defaultValue={product.display_name} required/></label><label className="field">ประเภท<select className="input" name="product_type" defaultValue={product.product_type}><option value="reagent">Reagent</option><option value="calibrator">Calibrator</option><option value="control">Control</option><option value="consumable">Consumable</option></select></label><label className="field">ขนาดบรรจุ<input className="input" name="packing_size_raw" defaultValue={product.packing_size_raw ?? ''}/></label><label className="field">หน่วยนับสต็อก<select className="input" name="base_stock_unit" defaultValue={product.base_stock_unit} required>{STOCK_UNITS.map(u=><option key={u.value} value={u.value}>{u.label}</option>)}{!isStockUnit(product.base_stock_unit)&&<option value={product.base_stock_unit}>{product.base_stock_unit}</option>}</select></label><label className="flex items-center gap-3 font-semibold text-sm"><input type="checkbox" name="active" defaultChecked={product.active}/> ใช้งานสินค้า</label><div className="sm:text-right"><SubmitButton className="button" label="บันทึกข้อมูลสินค้า" pendingLabel="กำลังบันทึก…"/></div></form>}</section>
    <section className="surface p-5 sm:p-7"><h2 className="text-lg font-extrabold mb-2">Identifiers</h2><p className="muted text-sm mb-5">REF, manufacturer barcode และรหัสมาตรฐานเก็บแยกชนิด</p><div className="grid gap-2">{identifiers.map(item => <div className="rounded-lg bg-surface-2 p-3" key={item.id}><div className="flex flex-wrap items-start justify-between gap-2"><div><span className="badge">{item.kind}</span><p className="font-mono text-sm mt-1 break-all">{item.value}</p><p className="muted text-xs">{item.source} · {item.approved ? 'ยืนยันแล้ว' : 'รอยืนยัน'}</p></div>{editable && item.kind !== 'REF_CURRENT' && <ConfirmForm action={deleteIdentifier} message="ลบ identifier นี้?" className="shrink-0"><input type="hidden" name="id" value={item.id}/><input type="hidden" name="product_id" value={id}/><SubmitButton className="button danger text-xs" label="ลบ" pendingLabel="กำลังลบ…"/></ConfirmForm>}</div>{editable && <details className="mt-2"><summary className="cursor-pointer text-sm font-bold text-brand min-h-11 flex items-center">แก้ไขค่า</summary><form action={saveIdentifier} className="grid sm:grid-cols-[180px_1fr_auto] gap-3 items-end"><input type="hidden" name="product_id" value={id}/><input type="hidden" name="id" value={item.id}/><label className="field">ชนิด<select className="input" name="kind" defaultValue={item.kind} disabled><option value={item.kind}>{item.kind}</option></select><input type="hidden" name="kind" value={item.kind}/></label><label className="field">ค่า<input className="input" name="value" defaultValue={item.value} required/></label><SubmitButton className="button secondary" label="บันทึก" pendingLabel="กำลังบันทึก…"/></form></details>}</div>)}{identifiers.length === 0 && <p className="muted text-sm">ยังไม่มี identifier</p>}</div>{editable && <form action={saveIdentifier} className="grid sm:grid-cols-[180px_1fr_auto] gap-3 items-end mt-6 pt-6 border-t border-line"><input type="hidden" name="product_id" value={id}/><label className="field">ชนิด<select className="input" name="kind"><option value="REF_LEGACY">REF เดิม</option><option value="MANUFACTURER_BARCODE">Manufacturer barcode</option><option value="GTIN">GTIN</option><option value="HIBC_PCN">HIBC PCN</option><option value="GS1_AI240">GS1 AI 240</option><option value="OTHER">Other</option></select></label><label className="field">ค่า<input className="input" name="value" required/></label><SubmitButton className="button" label="เพิ่มรหัส" pendingLabel="กำลังบันทึก…"/></form>}</section>
    <section className="surface p-5 sm:p-7"><h2 className="text-lg font-extrabold mb-2">Related Products</h2><p className="muted text-sm mb-5">ทิศทาง: สินค้านี้ → สินค้าเป้าหมายในคลังเดียวกัน</p><div className="grid gap-4">{relations.map(relation => <div key={relation.id} className="rounded-xl border border-line p-4"><div className="flex justify-between gap-3 flex-wrap mb-3"><div><span className="badge">{label(relationTypeLabels,relation.relation_type)}</span><p className="font-semibold mt-2">{optionMap.get(relation.target_product_id)?.product_code ?? relation.target_product_id} · {optionMap.get(relation.target_product_id)?.display_name ?? '—'}</p>{relation.source_kind === 'owner-approved' && <p className="muted text-xs mt-2">Owner-approved · {relation.source_review_id} · {relation.note}</p>}{relation.source_text && <p className="muted text-xs mt-1">Workbook said: {relation.source_text}</p>}</div>{editable && <ConfirmForm action={deleteRelation} message="ลบความสัมพันธ์ปัจจุบัน? เหตุการณ์ลบจะคงอยู่ใน audit log"><input type="hidden" name="id" value={relation.id}/><input type="hidden" name="source_product_id" value={id}/><SubmitButton className="button danger text-xs" label="ลบความสัมพันธ์" pendingLabel="กำลังลบ…"/></ConfirmForm>}</div>{editable && <details><summary className="cursor-pointer text-sm font-bold text-brand min-h-11 flex items-center">แก้ไข</summary><RelationEditor sourceId={id} options={options} relation={relation}/></details>}</div>)}{relations.length === 0 && <p className="muted text-sm">ยังไม่มีความสัมพันธ์ที่ยืนยันแล้ว</p>}{editable && <div className="mt-3"><h3 className="font-bold mb-3">เพิ่มความสัมพันธ์</h3><RelationEditor sourceId={id} options={options}/></div>}</div></section>
    <section className="surface p-5 sm:p-7"><h2 className="text-lg font-extrabold mb-4">Platforms / Analyzer</h2><div className="grid gap-2">{platforms.map(p => <div className="rounded-lg bg-surface-2 p-3 flex justify-between gap-3 items-center" key={p.id}><div><span className="badge">{p.ci_platforms?.display_name ?? '—'}</span>{p.source_kind === 'owner-approved' && <p className="muted text-xs mt-1">Owner-approved · {p.source_review_id}</p>}{p.source_text && <p className="muted text-xs mt-1">Workbook said: {p.source_text}</p>}</div>{editable && <ConfirmForm action={deletePlatform} message="ลบ platform mapping นี้?" className="shrink-0"><input type="hidden" name="id" value={p.id}/><input type="hidden" name="product_id" value={id}/><SubmitButton className="button danger text-xs" label="ลบ" pendingLabel="กำลังลบ…"/></ConfirmForm>}</div>)}{platforms.length === 0 && <p className="muted text-sm">ไม่มี Product → Platform mapping ที่ยืนยัน</p>}</div>{editable && <form action={savePlatform} className="grid sm:grid-cols-[1fr_1fr_auto] gap-3 items-end mt-6 pt-6 border-t border-line"><input type="hidden" name="product_id" value={id}/><label className="field">Platform / Group<select className="input" name="platform_id" required defaultValue=""><option value="">เลือก Platform</option>{platformOptions.map(p => <option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label><label className="field">หลักฐาน / หมายเหตุ<input className="input" name="source_text" placeholder="ข้อความต้นทางหรือคำอธิบาย"/></label><SubmitButton className="button" label="เพิ่ม Platform" pendingLabel="กำลังบันทึก…"/></form>}</section>
    <section className="surface p-5 sm:p-7"><h2 className="text-lg font-extrabold mb-4">Stock / LOT</h2><div className="grid gap-2">{balances.map(b => <div className="grid grid-cols-[1fr_auto] gap-3 rounded-lg bg-surface-2 p-3 text-sm" key={`${b.lot_id}:${b.location_id}`}><div><p className="font-bold">LOT {b.lot_number}</p><p className="muted">หมดอายุ {b.expiry_date} · {locationMap.get(b.location_id)?.code ?? '—'} · {locationMap.get(b.location_id)?.name ?? ''}</p></div><strong>{Number(b.balance).toLocaleString()}</strong></div>)}{balances.length === 0 && <p className="muted text-sm">ยังไม่มียอดคงเหลือ</p>}</div></section>
    <section className="surface p-5 sm:p-7"><h2 className="text-lg font-extrabold mb-3">ROP / Suggested Order</h2><p className="text-sm">โหมด {reorder?.mode??'ยังไม่ตั้งค่า'} · ใช้ได้ {Number(reorder?.usable_stock??0).toLocaleString()} {unitLabel(product.base_stock_unit)} · ROP {reorder?.rop==null?'ต้องตั้งค่า':`${reorder.rop} ${unitLabel(product.base_stock_unit)}`} · แนะนำสั่ง {reorder?.suggested_order==null?'ต้องตั้งค่า':`${reorder.suggested_order} ${unitLabel(product.base_stock_unit)}`}</p>{reorder?.missing_reason && <p className="muted text-sm mt-2">{reorder.missing_reason}</p>}<Link href={`/reorder?warehouse=${warehouse.code}&q=${encodeURIComponent(product.product_code)}`} className="button secondary mt-3">ดูการตั้งค่า</Link></section>
    <section className="surface p-5 sm:p-7"><h2 className="text-lg font-extrabold mb-3">ความเคลื่อนไหวล่าสุด</h2><div className="grid gap-2">{(movementResult.data??[]).map((m,i)=>{const tx=txMap.get(m.transaction_id);return <p key={`${m.transaction_id}:${i}`} className="border rounded-lg p-3 text-sm">{tx?.kind??'movement'} · {Number(m.quantity_delta)>0?'+':''}{m.quantity_delta} · {tx?.purpose??'—'} · {tx?.created_at?new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Bangkok'}).format(new Date(tx.created_at)):'—'}</p>;})}{!movementResult.data?.length && <p className="muted text-sm">ยังไม่มี movement</p>}</div></section>
    {importResolutions.length > 0 && <section className="surface p-5 sm:p-7"><h2 className="text-lg font-extrabold mb-2">Owner-approved import decisions</h2><p className="muted text-sm mb-4">เก็บค่าจาก workbook และการตัดสินที่อนุมัติแยกกัน</p><div className="grid gap-3">{importResolutions.map((resolution) => <article key={resolution.review_id} className="rounded-xl border border-line p-4"><p className="badge">{resolution.review_id} · {resolution.resolution_type}</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><p className="muted text-xs">Workbook said</p><p className="break-words text-sm font-semibold">{resolution.raw_source_value === null ? 'ว่างใน workbook' : String(resolution.raw_source_value)}</p></div><div><p className="muted text-xs">Owner approved</p><p className="break-words text-sm font-semibold">{approvedResolutionText(resolution)}</p></div></div><p className="muted mt-3 text-xs">{resolution.resolution_note} · {new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Bangkok'}).format(new Date(resolution.recorded_at))}</p></article>)}</div></section>}
    <section className="surface p-5 sm:p-7"><h2 className="text-lg font-extrabold mb-4">Provenance</h2><dl className="grid sm:grid-cols-2 gap-4 text-sm"><div><dt className="muted">ชีตต้นทาง</dt><dd className="font-semibold">{product.source_sheet || 'เพิ่มด้วยมือ'}</dd></div><div><dt className="muted">แถวต้นทาง</dt><dd className="font-semibold">{product.source_row ?? '—'}</dd></div></dl>{product.raw_source && <details className="mt-4"><summary className="cursor-pointer text-sm font-semibold min-h-11 flex items-center">ดูข้อมูลแถวดิบ</summary><pre className="text-xs whitespace-pre-wrap break-all bg-surface-2 p-4 rounded-xl">{JSON.stringify(product.raw_source,null,2)}</pre></details>}</section>
    {warehouse.role === 'admin' && <ConfirmForm action={deleteProduct} message="ลบสินค้าอย่างถาวร? ทำได้เฉพาะเมื่อยังไม่มี LOT หรือ invoice history และเหตุการณ์ลบจะถูก audit." className="surface p-5 sm:p-7 flex flex-wrap items-center justify-between gap-4"><input type="hidden" name="id" value={id}/><div><h2 className="font-extrabold">ลบสินค้า</h2><p className="muted text-sm mt-1">ใช้ได้เมื่อยังไม่มีประวัติการดำเนินงาน</p></div><SubmitButton className="button danger" label="ลบสินค้า" pendingLabel="กำลังลบ…"/></ConfirmForm>}
  </main>;
}
