import { requireAccess } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';
import { upsertUserAccess } from '@/app/actions/products';

type AccessRow = { user_id: string; warehouse_id: number; role: string; active: boolean; ci_user_profiles: { ephis_id: string } | null; ci_warehouses: { name: string } | null };

export default async function UsersPage({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string }> }) {
  const access = await requireAccess(); const params = await searchParams;
  const isAdminBoth = access.warehouses.some(w => w.code === 'CHE' && w.role === 'admin') && access.warehouses.some(w => w.code === 'IMM' && w.role === 'admin');
  if (!isAdminBoth) return <main className="grid gap-5"><div><p className="eyebrow">User access</p><h1 className="page-title">ผู้ใช้และสิทธิ์คลัง</h1></div><p className="error">หน้านี้ใช้ได้เฉพาะ Admin ที่มีสิทธิ์ทั้งสองคลัง</p></main>;
  const client = await createClient();
  const { data,error } = client ? await client.from('ci_user_access').select('user_id,warehouse_id,role,active,ci_user_profiles(ephis_id),ci_warehouses(name)').order('warehouse_id').order('role') : { data: [],error:null };
  const rows = (data ?? []) as unknown as AccessRow[];
  return <main className="grid gap-6 max-w-[1000px]"><div><p className="eyebrow mb-2">Identity / Authorization</p><h1 className="page-title">ผู้ใช้และสิทธิ์คลัง</h1><p className="muted mt-2 text-sm">ก่อนกำหนดสิทธิ์ ต้องสร้างบัญชีใน Supabase Auth แล้วใส่ Auth UUID จากระบบนั้น</p></div>{params.error && <p className="error" role="alert">{params.error}</p>}{params.saved && <p className="notice">บันทึกสิทธิ์แล้ว</p>}{error && <p className="error">{error.message}</p>}
    <form action={upsertUserAccess} className="surface p-5 sm:p-7 grid gap-4"><h2 className="font-extrabold text-lg">กำหนดสิทธิ์บัญชี</h2><div className="grid sm:grid-cols-2 gap-4"><label className="field">Supabase Auth user UUID<input className="input font-mono" name="user_id" required placeholder="UUID จาก Supabase Auth"/></label><label className="field">Ephis ID<input className="input" name="ephis_id" required/></label><label className="field">คลัง<select className="input" name="warehouse_id"><option value="1">CLINICAL CHEMISTRY</option><option value="2">IMMUNOLOGY</option></select></label><label className="field">Role<select className="input" name="role"><option value="viewer">Viewer</option><option value="staff">Staff</option><option value="supervisor">Supervisor</option><option value="admin">Admin</option></select></label></div><label className="flex gap-3 items-center text-sm font-semibold min-h-11"><input type="checkbox" name="active" defaultChecked/> เปิดสิทธิ์ในคลังที่เลือก</label><p className="notice text-sm">Ephis ID จะผูกกับ UUID ครั้งแรกและเปลี่ยนไม่ได้ใน RPC นี้ การตรวจสิทธิ์ทำด้วย Auth UUID และ RLS</p><div><button className="button" type="submit">บันทึกสิทธิ์</button></div></form>
    <section className="surface overflow-hidden"><div className="px-5 py-4"><h2 className="font-bold">สิทธิ์ที่กำหนด</h2></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Ephis ID</th><th>คลัง</th><th>Role</th><th>สถานะ</th><th>Auth UUID</th></tr></thead><tbody>{rows.map(row => <tr key={`${row.user_id}:${row.warehouse_id}`}><td className="font-bold">{row.ci_user_profiles?.ephis_id ?? '—'}</td><td>{row.ci_warehouses?.name ?? row.warehouse_id}</td><td>{row.role}</td><td>{row.active ? 'Active' : 'Disabled'}</td><td className="font-mono text-xs">{row.user_id}</td></tr>)}</tbody></table></div>{rows.length === 0 && <p className="muted p-5">ยังไม่มีการกำหนดสิทธิ์</p>}</section>
  </main>;
}
