import { requireAccess } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';
import { provisionUser } from '@/app/actions/users';
import { ChangePasswordDialog } from '@/components/change-password-dialog';
import { logUserMessage } from '@/lib/messages';
import { label, roleLabels } from '@/lib/labels';
import { SubmitButton } from '@/components/submit-button';
import { PositionCell } from '@/components/position-cell';

type AccessRow = { user_id: string; warehouse_id: number; role: string; active: boolean; ci_user_profiles: { ephis_id: string; display_name: string; active: boolean; position_title: string | null } | null; ci_warehouses: { name: string } | null };

export default async function UsersPage({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string }> }) {
  const access = await requireAccess(); const params = await searchParams;
  const isAdminBoth = access.warehouses.some(w => w.code === 'CHE' && w.role === 'admin') && access.warehouses.some(w => w.code === 'IMM' && w.role === 'admin');
  if (!isAdminBoth) return <main className="grid gap-5"><div><p className="eyebrow">User access</p><h1 className="page-title">ผู้ใช้และสิทธิ์คลัง</h1></div><p className="error">หน้านี้ใช้ได้เฉพาะผู้ดูแลระบบที่มีสิทธิ์ทั้งสองคลัง</p></main>;
  const client = await createClient();
  const { data,error } = client ? await client.from('ci_user_access').select('user_id,warehouse_id,role,active,ci_user_profiles(ephis_id,display_name,active,position_title),ci_warehouses(name)').order('user_id').order('warehouse_id') : { data: [],error:null };
  const rows = (data ?? []) as unknown as AccessRow[];
  // Phones get one card per person (the table has one row per person × warehouse).
  const users = [...Map.groupBy(rows, row => row.user_id)].map(([id, access]) => ({ id, access, profile: access[0].ci_user_profiles, ephisId: access[0].ci_user_profiles?.ephis_id ?? '—', name: access[0].ci_user_profiles?.display_name ?? '' }));
  return <main className="grid gap-6 max-w-[1000px]"><div><p className="eyebrow mb-2">Identity / Authorization</p><h1 className="page-title">ผู้ใช้และสิทธิ์คลัง</h1><p className="muted mt-2 text-sm">ระบบสร้าง internal Auth identity จาก Ephis ID ให้อัตโนมัติ บัญชีเดิมแก้ชื่อ บทบาท คลัง และสถานะได้โดยเว้นรหัสผ่านว่าง</p></div>{params.error && <p className="error" role="alert">{params.error}</p>}{params.saved && <p className="notice" role="status">บันทึกผู้ใช้และสิทธิ์แล้ว</p>}{error && <p className="error" role="alert">{logUserMessage('admin-users', error)}</p>}
    <form action={provisionUser} className="surface p-5 sm:p-7 grid gap-4"><h2 className="font-extrabold text-lg">Provision / ปรับสิทธิ์</h2><div className="grid sm:grid-cols-2 gap-4"><label className="field">Ephis ID<input className="input" name="ephis_id" autoComplete="off" required maxLength={64}/></label><label className="field">ชื่อที่แสดง<input className="input" name="display_name" autoComplete="name" required maxLength={120}/></label><label className="field">บทบาท<select className="input" name="role" defaultValue="staff"><option value="viewer">ดูอย่างเดียว (Viewer)</option><option value="staff">เจ้าหน้าที่ (Staff)</option><option value="supervisor">หัวหน้างาน (Supervisor)</option><option value="admin">ผู้ดูแลระบบ (Admin)</option></select></label><label className="field">รหัสผ่านเริ่มต้น (เฉพาะบัญชีใหม่)<input className="input" name="initial_password" type="password" autoComplete="new-password" minLength={12}/></label></div><fieldset className="grid sm:grid-cols-2 gap-2"><legend className="field-label mb-2">คลังที่อนุญาต</legend><label className="flex items-center gap-3 min-h-11"><input type="checkbox" name="warehouse_ids" value="1" defaultChecked/>CLINICAL CHEMISTRY</label><label className="flex items-center gap-3 min-h-11"><input type="checkbox" name="warehouse_ids" value="2"/>IMMUNOLOGY</label></fieldset><label className="flex gap-3 items-center text-sm font-semibold min-h-11"><input type="checkbox" name="active" defaultChecked/>เปิดใช้งานผู้ใช้และสิทธิ์ที่เลือก</label><p className="notice text-sm">การค้นบัญชีและบันทึกสิทธิ์ใช้ Ephis ID ฝั่ง server/database; UUID ไม่รับจาก browser และ password จะไม่ถูกเปลี่ยนเมื่อแก้บัญชีเดิม</p><div><SubmitButton className="button min-h-11" label="บันทึกผู้ใช้" pendingLabel="กำลังบันทึก…"/></div></form>
    <section className="surface overflow-hidden"><div className="px-5 py-4"><h2 className="font-bold">สิทธิ์ที่กำหนด</h2></div><div className="desktop-table table-wrap"><table className="data-table"><thead><tr><th>Ephis ID / ชื่อ</th><th>คลัง</th><th>บทบาท</th><th>สถานะ</th><th>ตำแหน่ง (ใช้บนรายงาน)</th><th>รหัสผ่าน</th></tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.user_id}:${row.warehouse_id}`}><td><span className="font-bold">{row.ci_user_profiles?.ephis_id ?? '—'}</span><span className="block muted text-xs">{row.ci_user_profiles?.display_name ?? ''}</span></td><td>{row.ci_warehouses?.name ?? row.warehouse_id}</td><td>{label(roleLabels,row.role)}</td><td>{row.ci_user_profiles?.active && row.active ? 'ใช้งาน' : 'ปิดใช้งาน'}</td><td>{row.ci_user_profiles && rows[index - 1]?.user_id !== row.user_id && <PositionCell userId={row.user_id} name={row.ci_user_profiles.display_name} position={row.ci_user_profiles.position_title} />}</td><td>{row.ci_user_profiles && rows[index - 1]?.user_id !== row.user_id && <ChangePasswordDialog ephisId={row.ci_user_profiles.ephis_id} displayName={row.ci_user_profiles.display_name} />}</td></tr>)}</tbody></table></div><div className="mobile-card-list px-4 pb-4">{users.map(user => <article key={user.id} className="rounded-xl border border-line p-4 grid gap-2"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-bold">{user.ephisId}</p><p className="muted text-sm truncate">{user.name}</p>{user.profile && <div className="mt-2"><PositionCell userId={user.id} name={user.profile.display_name} position={user.profile.position_title} /></div>}</div>{user.profile && <ChangePasswordDialog ephisId={user.profile.ephis_id} displayName={user.profile.display_name} />}</div><ul className="grid gap-1 text-sm">{user.access.map(row => <li key={row.warehouse_id} className="flex justify-between gap-2"><span>{row.ci_warehouses?.name ?? row.warehouse_id}</span><span className="text-right">{label(roleLabels,row.role)} · {row.ci_user_profiles?.active && row.active ? 'ใช้งาน' : 'ปิดใช้งาน'}</span></li>)}</ul></article>)}</div>{rows.length === 0 && <p className="muted p-5">ยังไม่มีการกำหนดสิทธิ์</p>}</section>
  </main>;
}
